In [1]:
import pandas as pd
import numpy as np
import sys
import numpy as np
import math

In [2]:
loc_count = 8
veh_count = 8
maxDep = 2

class Vehicles():
 
    def __init__(self, quantity):
        self.V = quantity
        self.stats = [[0 for column in range(7)]
                      for row in range(quantity)]
        self.route_all = [[0 for column in range(1)]
                      for row in range(quantity)]
        self.route_dist_all = [[0 for column in range(1)]
                      for row in range(quantity)]
        self.route = [[0 for column in range(1)]
                      for row in range(quantity)]
        self.route_dist = [[0 for column in range(1)]
                      for row in range(quantity)]

In [3]:
ev = Vehicles(veh_count)
q = np.genfromtxt("EV.csv", delimiter=',')
q = q.tolist()
ev.stats = q

r = np.genfromtxt("Nodes.csv", delimiter=',')
r = r.tolist()
r[0][0] = 0

In [4]:
from collections import defaultdict
   
class Graph2:
   
    def __init__(self, vertices):
        self.V = vertices 

        self.graph = defaultdict(list) 
   
    def addEdge(self, u, v):
        self.graph[u].append(v)
   
    
    def printAllPathsUtil(self, u, d, visited, path, id):
  
        visited[u]= True
        path.append(u)
        
        # current path[] is below
        if u == d:
            path2 = path.copy()
            dist =0
            for i in range(len(path2)-1) :
              dist = dist + r[path2[i]][path2[i+1]]
            
            #For all possible paths
            if ev.route_dist_all[id][0] == 0:
              ev.route_dist_all[id][0] = dist
              ev.route_all[id][0] = path2
            else :
              ev.route_dist_all[id].append(dist)
              ev.route_all[id].append(path2)
            
           

        else:
            for i in self.graph[u]:
                if visited[i]== False and r[u][i] < 100 * ev.stats[id][4]:
                    self.printAllPathsUtil(i, d, visited, path, id)
                      
        path.pop()
        visited[u]= False
   
    def printAllPaths(self, s, d, id):
  
        visited =[False]*(self.V)

        path = []
  
        self.printAllPathsUtil(s, d, visited, path, id)

In [5]:
no_Car = 0
for i in range(veh_count):
    if ev.stats[i][4] == 0:
        no_Car = no_Car + 1

In [7]:
t = Graph2(loc_count)
for i in range(loc_count):
    for j in range(loc_count) :
        if r[i][j] < 1000 :
            t.addEdge(i,j)

for id in range(no_Car) :
    t.printAllPaths(int(ev.stats[id][0]-1),int(ev.stats[id][1]-1),id)

In [6]:
print(ev.route_dist_all)

[[0], [0], [0], [0], [0], [0], [0], [0]]


In [7]:
for id in range(veh_count) :
    sort_arg = np.argsort(ev.route_dist_all[id])
    for j in range(min(maxDep,len(ev.route_all[id]))) :
        n = sort_arg[j]
    if ev.route_dist[id][0] == 0:
        ev.route_dist[id][0] = ev.route_dist_all[id][n]
        ev.route[id][0] = ev.route_all[id][n]
    else :
        ev.route_dist[id].append(ev.route_dist_all[id][n])
        ev.route[id].append(ev.route_all[id][n])

In [8]:
ev.route_dist

[[0], [0], [0], [0], [0], [0], [0], [0]]

In [9]:
batc = np.zeros((loc_count,veh_count), dtype=int)
battery_needed = [0.]*veh_count
path = []
current_battery = [0]*veh_count
visited = [[-1 for column in range(1)]
                     for row in range(loc_count)]

In [10]:
#Assuming one path below
for id in range(no_Car):
    path.append(ev.route[id][0])
    battery_needed[id] = max(0,math.ceil(ev.route_dist[id][0]/ev.stats[id][4] - ev.stats[id][2]))
    current_battery[id] = int(ev.stats[id][2])



path_optimal = []
batc_optimal = np.zeros((veh_count,loc_count), dtype=int)
time_optimal = [[0 for column in range(1)]
                for row in range(veh_count)]
minimum_time_achieved = sys.maxsize
charge_start_time = [[-1 for column in range(loc_count)]
                      for row in range(veh_count)]
charge_end_time = [[-1 for column in range(loc_count)]
                    for row in range(veh_count)]

In [11]:

time = [[0 for column in range(1)]
          for row in range(veh_count)]
charging_start_time = [[-1 for column in range(loc_count)]
                         for row in range(veh_count)]
charging_end_time = [[-1 for column in range(loc_count)]
                         for row in range(veh_count)]

In [12]:
path

[]

In [13]:
def final_time (batc,path) :

    time = [[0 for column in range(1)]
          for row in range(veh_count)]
    charging_start_time = [[-1 for column in range(loc_count)]
                         for row in range(veh_count)]
    charging_end_time = [[-1 for column in range(loc_count)]
                         for row in range(veh_count)]

for id in range(veh_count) :
    if path == []:
        break
    for j in range(len(path[id])) :
        if j==0:
            time[id][0] = 0
    else :
        time[id][0] = 1
instances = [0]*loc_count
vehicle_at_instance = [[-1 for column in range(1)]
                     for row in range(loc_count)]
for i in range(loc_count):
    for j in range(veh_count):
        if batc[j][i] > 0 :
            instances[i] += 1
        if vehicle_at_instance[i][0] == -1:
            vehicle_at_instance[i][0] = j
        else:
            vehicle_at_instance[i].append(j)


In [14]:
car_instances = [0]*veh_count
for i in range(veh_count):
    for j in range(loc_count):
        if batc[i][j] > 0 :
            car_instances[i] += 1

In [15]:
print("instances",instances)
print("car_instances",car_instances)

instances [0, 0, 0, 0, 0, 0, 0, 0]
car_instances [0, 0, 0, 0, 0, 0, 0, 0]


In [21]:
cost = [0]*veh_count
for id in range(veh_count):
    for i in range(len(path)):
        cost[id] = cost[id] + r[path[id][i]][path[id][i+1]]

print("cost",cost)

cost [0, 0, 0, 0, 0, 0, 0, 0]


In [23]:
for id in range(veh_count):
    if cost[id] < ev.stats[id][2]:
        for i in range(len(path)-1):
            batc[id][path[id][i+1]] = batc[id][path[id][i]] - r[path[id][i]][path[id][i+1]]
    else:
        for i in range(len(path[id])-1):
            batc[id][path[id][i+1]] = batc[id][path[id][i]] - r[path[id][i]][path[id][i+1]]
        batc[id][path[id][i+1]] = batc[id][path[id][i+1]] - (cost[id] - ev.stats[id][2])

print("batc",batc)

batc [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
